var bullshitTerms = [
    '(market|goal|community|quality|results|sales|user|customer' +
        '|subject|role|service|client|process|business)' +
        '.(centric(ity)?|facing|oriented|driven|focused|assessment|service)',
    '24/7',
    '(benefit|gap) analysis',
    '(business.(to|2).business)'
    '(high|mass).impact',
    '(mission|time).critical',
    '(search engine )?optimization',
    '(total cost of )?ownership',
    'a-b testing',
    'accessib(le|ility)',
    'accessibility'
    'acquisition',
    'action items?',
    'advantages?',
    'aggregate',
    'agile development'
    'analytics?',
    'application service providers?',
    'assets?',
    'authoritative',
    'automated',
    'b2b',
    'back to the drawing board',
    'ball.?park',
    'band.aid',
    'bandwidth',
    'benchmark',
    'best.of.breed',
    'best.practice',
    'big picture',
    'big.data',
    'bottom line',
    'bottom.up',
    'brain.?(dump|storm)',
    'brand(s?|ing|ed)',
    'burn.rates?',
    'business development'
    'business.(cases|plans)?',
    'buzz',
    'call to action',
    'capacity',
    'capitalize',
    'center of excellence',
    'challenges?',
    'change agent',
    'circle the wagons',
    'collaborat(e|ion)',
    'communicat(e|ion)',
    'compelling',
    'competitive( advantage)?',
    'connect the dots',
    'content (management|marketing|migration)'
    'content management',
    'contextual(ly)?',
    'contingency plan',
    'control group',
    'convergent',
    'conversion rate optimization'
    'conversion',
    'core business',
    'core competenc(y|ies)',
    'corporate websites?'
    'cost control',
    'cost-effective',
    'cost/benefit',
    'craftsmanship',
    'critical path',
    'crm',
    'cross-channel'
    'cross.sell',
    'crowd.?(fund(s?|ed|ing)|sourc(ed|e|ing))',
    'customer relationship management'
    'cutting.edge',
    'data mining',
    'de-dupe',
    'deep dive',
    'delight the customers?',
    'deliverables?',
    'demographic',
    'digital(es)? marketing'
    'digitale? transformaion'
    'discovery',
    'disrupt(ive)?',
    'diversity',
    'downsize',
    'drill down',
    'drink the kool-aid',
    'drop the ball',
    'drop.?in',
    'due dilligence',
    'dynamic',
    'e-?(business|commerce|tailers)',
    'e-?commerce'
    'ecosystems?',
    'efficien(t|cy)',
    'elaboration',
    'elephant in the room',
    'elevator pitch',
    'emerging markets',
    'empower(ment)?',
    'end of the day',
    'end to end',
    'engag(e|ing)',
    'engage(ments?)?',
    'enhance',
    'enterprise',
    'erp',
    'eta',
    'etched in stone',
    'exceed expectations',
    'expectations',
    'experiences',
    'expertise',
    'experts?',
    'exposure',
    'eyeballs',
    'facilitat(e|or)',
    'fast track',
    'fault.tolerant',
    'first to market',
    'flexibility',
    'followup',
    'foot view',
    'front lines',
    'full benefit',
    'functional',
    'game plan',
    'geo-behavioral'
    'go public',
    'go to market',
    'goals?',
    'going forward',
    'google juice',
    'graceful.degradation',
    'gradual.enhancement',
    'granular',
    'grow',
    'growth',
    'guidance',
    'hardball',
    'having said that',
    'heads.up',
    'heavy.lifting',
    'herding cats',
    'high.level',
    'impactful',
    'impeccable',
    'implementation',
    'in a nutshell',
    'incent',
    'incentivize',
    'increase the odds',
    'innovat(e|ed|ion|ive|ing|or)',
    'inspir(e|ing|ation)',
    'integrat(e|ed|ion)',
    'intellectual property',
    'internet of things',
    'intuitive',
    'knowledge base',
    'knowledge transfer',
    'landing pages?',
    'lead the field',
    'leadership',
    'legacy',
    'lessons learned',
    'level playing field',
    'level set',
    'leverage',
    'look.(&|and).feel',
    'low-hanging fruit',
    'm2m',
    'market leader',
    'market window',
    'marketing collateral',
    'maximize',
    'measurement',
    'methodolog(y|ies)',
    'metrics',
    'middleware',
    'milestone',
    'mind share',
    'mind shower',
    'mindset',
    'mindshare',
    'monetize',
    'moving forward',
    'multi.channel'
    'multifaceted',
    'multitask(ing?)',
    'negotiated',
    'networking',
    'new breed',
    'new economy',
    'next level',
    'niches?',
    'no-brainer',
    'non-traditional management',
    'objectives',
    'occupy the field',
    'off.site',
    'off.the.(radar|shelf)',
    'on board',
    'on the (back end|radar screen|same page)',
    'one to one',
    'online marketing'
    'open data'
    'opportunit(y|ies)',
    'optimal',
    'out(side)?.of.the.(box|loop)',
    'outsourc(e|ed|ing)',
    'paradigms?( shift)?',
    'partner(ships?)?',
    'patent',
    'performance indicators',
    'personalization',
    'perspective',
    'phase',
    'phased approach',
    'pipeline',
    'planning horizon',
    'platforms?',
    'plug.?in',
    'prioritized?',
    'proactive',
    'problem space',
    'processes',
    'professional.ethics'
    'profit(ability)?',
    'project management'
    'prominent',
    'promotion',
    'promotional collateral',
    'proof.of.concept',
    'proprietary',
    'push the envelope',
    'push.back',
    'quick win',
    'rais(e|ing) the bar',
    'ramp.up',
    'reach out',
    'reactivation',
    'real.time',
    'real.world',
    'reconfigure',
    'red flag',
    'reengineering',
    'reinvent(ing)? the(.square)? wheel',
    'reinvigorate',
    'relationship management',
    'relevance',
    'repurpose',
    'resource allocation',
    'responsive',
    'restructuring',
    'retention',
    'return on investment',
    'reus(e|ability)',
    'revenue',
    'reverse.engineer',
    'revisit',
    'road ?map',
    'robust',
    'roi',
    'run the numbers',
    'scale',
    'scenarios?',
    'scope',
    'seamless',
    'secret sauce',
    'segment',
    'self-managed team',
    'seo',
    'shareholder value',
    'single-source responsibility',
    'skill sets?',
    'smoke (&|and) mirrors',
    'social media'
    'social(.media|.gaming|.networks?)',
    'solutions?',
    'soup to nuts',
    'sow',
    'stakeholder',
    'start.up?',
    'statement of work',
    'sticky-?ness',
    'strateg(y|ic|ize)',
    'streamline',
    'success(ful)?',
    'sustainab(le|ility)',
    'synerg(y|ies)',
    'tailwinds?',
    'take offline',
    'talking points',
    'target (audience|group)',
    'targeted',
    'tasked',
    'tco',
    'team.building',
    'team.player',
    'teamwork',
    'technologies',
    'testmanagement'
    'that being said',
    'time.to.market',
    'timelines?',
    'top of the game',
    'top.down',
    'total quality',
    'touch applications'
    'touch.base',
    'touchpoints',
    'traction',
    'trends?',
    'turnkey',
    'unique approach',
    'up-?sell',
    'up.to.speed',
    'upside',
    'user centered design'
    'user experience'
    'user.experience',
    'user.friendly',
    'utiliz(e|ation)',
    'value-added',
    'valueable',
    'values?',
    'vertical market',
    'viral',
    'virtual(ization)?',
    'visibility',
    'vision',
    'walk the talk',
    'wearables?'
    'web.analytics'
    'web.enabled',
    'win-win',
    'wisdom of crowds',
    'workflow',
    'workshop',
    'world.?class',
    'wow.factor',

    // technical bullshit
    'cloud',
    '(object|aspect).oriented',
    '(framework|platform).agnostic',
    '(front.?end.|ui.)?framework',
    'html5',
    'mv(c|p)',
    'nosql',
    'off-?line',
    'oop',
    'web (2|3)\\.0'
];
