var bullshitTerms = [
    '(market|goal|community|quality|results|sales|user|customer|object|subject|aspect|role|service|client)' +
    '.(centric|facing|oriented|service|driven|focused)',
    '24/7',
    'a-b testing',
    'accessib(le|ility)',
    'acquisition',
    'action items?',
    'advantages?',
    'aggregate',
    '(framework|platform).agnostic',
    'analytics?',
    'application service providers?',
    'assets?',
    'authoritative',
    'automated',
    'b2b',
    'back to the drawing board',
    'ball.?park',
    'band.aid',
    'bandwidth',
    'benchmark',
    'benefit analysis',
    'best.of.breed',
    'best.practice',
    'big.data',
    'big picture',
    'bottom line',
    'bottom.up',
    'brain.?storm',
    'brain.?dump',
    'brand(s?|ing|ed)',
    'burn.rates?',
    'business.(cases|plans)?',
    'business.centric(ity)?',
    'buzz',
    'call to action',
    'capacity',
    'capitalize',
    'center of excellence',
    'challenges?',
    'change agent',
    'circle the wagons',
    'cloud.based',
    'collaborat(e|ion)',
    'communicat(e|ion)',
    'compelling',
    'competitive( advantage)?',
    'connect the dots',
    'content management',
    'contingency plan',
    'control group',
    'convergent',
    'conversion',
    'core business',
    'core competenc(y|ies)',
    'cost-effective',
    'cost/benefit',
    'craftsmanship',
    'critical path',
    'crm',
    'cross.sell',
    'crowd.?(fund(s?|ed|ing)|sourc(ed|e|ing))',
    'customer service',
    'cutting.edge',
    'data mining',
    'deep dive',
    'delight the customers?',
    'deliverables?',
    'demographic',
    'discovery',
    'diversity',
    'downsize',
    'drill down',
    'drink the kool-aid',
    'drop.?in',
    'drop the ball',
    'due dilligence',
    'dynamic',
    'e-?(business|commerce|tailers)',
    'ecosystems?',
    'efficien(t|cy)',
    'elaboration',
    'elephant in the room',
    'elevator pitch',
    'emerging markets',
    'empower(ment)?',
    'end of the day',
    'end to end',
    'engage',
    'enhance',
    'enterprise',
    'eta',
    'etched in stone',
    'exceed expectations',
    'expectations',
    'experiences',
    'exposure',
    'eyeballs',
    'facilitate',
    'facilitator',
    'fast track',
    'fault.tolerant',
    'first to market',
    'flexibility',
    'focused',
    'followup',
    'foot view',
    '(front.?end.|ui.)?frame.?work',
    'front lines',
    'functional',
    'full benefit',
    'game plan',
    'gap analysis',
    'go public',
    'go to market',
    'goals',
    'going forward',
    'google juice',
    'graceful.degradation',
    'gradual.enhancement',
    'granular',
    'growth',
    'grow',
    'guidance',
    'hardball',
    'having said that',
    'heads.up',
    'heavy.lifting',
    'herding cats',
    'high.level',
    '(high|mass).impact',
    'html5',
    'impactful',
    'implementation',
    'in a nutshell',
    'incent',
    'incentivize',
    'innovat(e|ed|ion|ive|ing)',
    'integrat(e|ed|ion)',
    'internet of things',
    'intellectual property',
    'intuitive',
    'knowledge base',
    'knowledge transfer',
    'landing pages?',
    'lead the field',
    'leadership',
    'legacy',
    'lessons learned',
    'level playing field',
    'level set',
    'leverage',
    'low-hanging fruit',
    'look.(&|and).feel',
    'market leader',
    'market window',
    'marketing collateral',
    'maximize',
    'measurement',
    'methodolog(y|ies)',
    'metrics',
    'middleware',
    'milestone',
    'mind share',
    'mind shower',
    'mindset',
    'mindshare',
    'mission.critical',
    'monetize',
    'moving forward',
    'multitask',
    'multitasking',
    'mvc',
    'mvp',
    'negotiated',
    'networking',
    'new economy',
    'next level',
    'niche',
    'niches',
    'no-brainer',
    'non-traditional management',
    'nosql',
    'objectives',
    'occupy the field',
    'off.site meeting',
    'off.the.(radar|shelf)',
    'off-?line',
    'on board',
    'on the (back end|radar screen|same page)',
    'one to one',
    'oop',
    'opportunit(y|ies)',
    'optimization',
    'out(side)?.of.the.(box|loop)',
    'outsourc(e|ed|ing)',
    'ownership',
    'paradigm shift',
    'paradigms?',
    'partnerships?',
    'partner',
    'patent',
    'performance indicators',
    'personalization',
    'perspective',
    'phase',
    'phased approach',
    'pipeline',
    'planning horizon',
    'plug.?in',
    'prioritized?',
    'proactive',
    'problem space',
    'process assessment',
    'processes',
    'process-centric',
    'profitability',
    'profit',
    'promotional collateral',
    'promotion',
    'proprietary',
    'proof.of.concept',
    'push the envelope',
    'pushback',
    'quick win',
    'rais(e|ing) the bar',
    'ramp.up',
    'relationship management',
    'responsive',
    'engagements?',
    'engage',
    'reach out',
    'reactivation',
    'real.time',
    'real.world',
    'reconfigure',
    'red flag',
    'reengineering',
    'reinvent(ing)? the(.square)? wheel',
    'reinvigorate',
    'relevance',
    'repurpose',
    'resource allocation',
    'restructuring',
    'retention',
    'return on investment',
    'reusability',
    'reuse',
    'revenue',
    'reverse.engineer',
    'revisit',
    'road ?map',
    'robust',
    'roi',
    'run the numbers',
    'scale',
    'scenarios?',
    'scope',
    'seamless',
    'search engine optimization',
    'secret sauce',
    'segment',
    'self-managed team',
    'seo',
    'shareholder value',
    'single-source responsibility',
    'skill sets?',
    'smoke (&|and) mirrors',
    'social(.media|.gaming|.networks?)',
    'solutions?',
    'soup to nuts',
    'sow',
    'stakeholder',
    'startup',
    'statement of work',
    'sticky-?ness',
    'strateg(y|ic|ize)',
    'streamline',
    'success',
    'sustainab(le|ility)',
    'synerg(y|ies)',
    'tailwinds?',
    'take offline',
    'talking points',
    'target (audience|group)',
    'targeted',
    'tasked',
    'tco',
    'team building',
    'team player',
    'teamwork',
    'technologies',
    'technology solutions',
    'that being said',
    'time.to.market',
    'time.critical',
    'timelines?',
    'top.down',
    'top of the game',
    'total cost of ownership',
    'total quality',
    'touch.base',
    'touchpoints',
    'traction',
    'turnkey',
    'up.to.speed',
    'up-?sell',
    'upside',
    'user.friendly',
    'user.experience',
    'utiliz(e|ation)',
    'unique approach',
    'values?',
    'value-added',
    'vertical market',
    'viral',
    'virtual(ization)?',
    'visibility',
    'vision',
    'walk the talk',
    'web (2|3)\\.0',
    'web.enabled',
    'win-win',
    'window of opportunity',
    'wisdom of crowds',
    'workflow',
    'workshop',
    'world.?class',
    'wow.factor'
];
